# neuts-main/Dockerfile.gpu
FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app

WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y --no-install-recommends \
    git ffmpeg libsndfile1 build-essential libopenblas-dev espeak-ng \
    && rm -rf /var/lib/apt/lists/*

COPY neutts-main/requirements.txt ${APP_HOME}/

RUN pip install --upgrade pip \
 && if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

COPY neutts-main/ ${APP_HOME}/

RUN mkdir -p /app/data /app/logs

ENV PORT=8000 \
    BACKBONE_PATH=/app/data/neutts-romanian-finetune/checkpoint-370000 \
    BACKBONE_DEVICE=cuda \
    CODEC_DEVICE=cuda

EXPOSE ${PORT}


CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info"]
